version: '3.8'

services:
  php:
    image: php:8.1-apache
    container_name: book_php
    ports:
      - "8080:80"
    volumes:
      - ./database:/data
      - ./src:/var/www/html
    depends_on:
      - sqlite

  sqlite:
    image: alpine:latest
    volumes:
      - ./database:/data
    command: sh -c "apk --no-cache add sqlite && cp /data/initial-db.sqlite /data/db.sqlite && chmod -R 777 /data/db.sqlite && sqlite3 /data/db.sqlite < /data/init.sql && tail -f /dev/null"
    container_name: book_sqlite

