version: '3.8'

services:
  php:
    image: php:8.1-apache
    container_name: book_php
    ports:
      - "8080:80"
    volumes:
      - ./database:/data
      - ./src:/var/www/html
    depends_on:
      - sqlite

  sqlite:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
        - ./database:/data
    command: tail -f /dev/null
    container_name: sqlite

